### ISSUE TITLE
OpenGL texture binding to HTML canvas

### ISSUE THREAD

**Issue by zivsha** [boyanio/angular-wasm#1]
Hi,
Awesome project, worked out of the box! (only issue I have is that "Home" routing does not work)

I'm new to WebAssemblies (and to be honest, to Angular as well) but have a fairly good understanding of how things work and bind together (for both frameworks).

I'm trying to understand how the `3d-cube` example works, but I can't figure out a few things:

1. How is `main(argc, argv)` being invoked? 
    After writing the above question I paused writing and started digging a bit more to figure this one on my own, so it would be nice to get a confirmation:

    > Each of the objects extend `EmWasmComponent` which calls `instantiateJs` to creates a `script` element in the HTML document which reference the path to the JS file that was created by `emcc`. This JS code invokes `main` 

2. How is the `canvas` of the 3d-cube bound to OpenGL's texture?

Thanks

**Comment by boyanio** [comment]
Hi @zivsha 

1. To initialize a WebAssembly module, you need to call `WebAssembly.instantiate`. When compiling C/C++ code with emscripten, you get generated JavaScript glue code to initialize your WebAssembly module instead. This generated JavaScript glue code calls `main` (if exists).

2. As WebAssembly does not support direct access to Web APIs or DOM, you need to wrap them in JavaScript calls. Emscripten generates such wrapped glue code, so that it is transparent for the C/C++ developer. In C/C++ you would use OpenGL, which gets "translated" to WebGL calls. You can see these calls in the generated JavaScript glue code too.

**Comment by zivsha** [comment]
@boyanio thank you!
So in your C++ code you create a window with a size of 500x500 which renders the cube and texture using (eventually) WebGL, and emscripten creates the glue to the DOM but does it know where to position the window? what am I missing here?

**Comment by boyanio** [comment]
There are different OpenGL versions. There is no 1:1 mapping between OpenGL and WebGL, you can read about Emscripten's support for OpenGL [here](https://kripken.github.io/emscripten-site/docs/porting/multimedia_and_graphics/OpenGL-support.html).

The code for the 3D cube is not written by me, I have found it somewhere on the web and I have modified it a bit to compile it to WebAssembly. On the web it makes no sense to manipulate windows, so what happens in reality is you manipulate the canvas. You can see the source code for `glutInitWindowSize` [here](https://github.com/kripken/emscripten/blob/df84567d01fb9243b8a79f77601cda6f8f0783fc/src/library_glut.js#L402).

**Comment by boyanio** [comment]
It is possible to have multiple OpenGL applications compiled to WebAssembly and each of them will use a separate canvas

**Comment by zivsha** [comment]
Thank you!
